services:
  postgres:
    image: postgres:16
    container_name: pg_fastapi_app_dev
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - pg_fastapi_app_vol_dev:/var/lib/postgresql/data
    networks:
      - fastapi_app_net_dev

volumes:
  pg_fastapi_app_vol_dev:

networks:
  fastapi_app_net_dev: