"""add tables to restaurant

Revision ID: 58045af24b3c
Revises: c603b0767818
Create Date: 2025-07-03 18:33:43.154229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58045af24b3c'
down_revision: Union[str, None] = 'c603b0767818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.Enum('terraza', 'interior', 'parque', 'jardín interno', 'jardín externo', name='tablelocationenum'), nullable=False),
    sa.Column('restaurant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id','restaurant_id')
    )
    op.create_index(op.f('ix_restaurant_id'), 'restaurant', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_id'), table_name='restaurant')
    op.drop_table('table')
    # Eliminar también el ENUM nativo
    op.execute("DROP TYPE IF EXISTS tablelocationenum;")
    # ### end Alembic commands ###
