"""create_menu_and_dish_tables

Revision ID: 819bcbef048d
Revises: c603b0767818
Create Date: 2025-07-04 08:57:33.938686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '819bcbef048d'
down_revision: Union[str, None] = 'c603b0767818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_id'), table_name='restaurant')
    op.drop_table('restaurant')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_table('restaurant',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('opening_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('closing_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_pkey'))
    )
    op.create_index(op.f('ix_restaurant_id'), 'restaurant', ['id'], unique=True)
    # ### end Alembic commands ###
