from enum import Enum

class ExceptionInfrastructureType(Enum):
    BAD_REQUEST = "BAD_REQUEST"
    CONFLICT = "CONFLICT"
    PERSISTENCE = "PERSISTENCE"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    NOT_REGISTERED = "NOT_REGISTERED"
    INTERNAL_SERVER_ERROR="INTERNAL_SERVER_ERROR"
